function makeRTTplot(obj,isBuckyPlot) 

if isBuckyPlot
    obj.RTTsidebar = uipanel('Units', 'normalized','Position',[.751 ,.045 .249 .96],...
        'BorderType','none');
else
    obj.RTTsidebar = uipanel('Units', 'normalized','Position',[.751 0 .249 1],...
        'BorderType','none');
end

if isBuckyPlot
    obj.evLabel = uicontrol('Units','normalized','Style','text','String','eV',...
        'HorizontalAlignment','center','Position',[.765 .96 .021 .02]);
    colorbar('position',[ .765 .08 .022 .87 ]);
else
    obj.evLabel = uicontrol('Units','normalized','Style','text','String','eV',...
        'HorizontalAlignment','center','Position',[.765 .94 .021 .03]);
    colorbar('position',[ .765 .03 .022 .9 ]);
end


% ========================
%  temp selection buttons
% ========================

tempSelect = uipanel('Parent',obj.RTTsidebar,...
    'Position',[.3 .808 .658 .173 ]);

htext1 = uicontrol('parent',tempSelect,'Units', 'normalized','HorizontalAlignment','center','FontWeight','bold',...
    'FontUnits','normalized','FontSize',.8,'Style','text','String','Temp','Position',[ 0 , .78 , 1 , .17 ]);

obj.noTemp = uicontrol('Style','togglebutton','String','none','parent',tempSelect,...
    'FontWeight','bold','FontUnits','normalized','FontSize',.6,'Callback',...
    {@(src,event)changeTemp(obj,src)},'Units','normalized','Position',[ .08 , .56 , .4 , .2],'HandleVisibility','off');
obj.te2a   = uicontrol('Style','togglebutton','String','elec','parent',tempSelect,...
    'FontWeight','bold','FontUnits','normalized','FontSize',.6,'Callback',...
    {@(src,event)changeTemp(obj,src)},'Units','normalized','Position',[ .55 , .56 , .4 , .2],'HandleVisibility','off');
obj.tr2a   = uicontrol('Style','togglebutton','String','rad','parent',tempSelect,...
    'FontWeight','bold','FontUnits','normalized','FontSize',.6,'Callback',...
    {@(src,event)changeTemp(obj,src)},'Units','normalized','Position',[ .08 , .31 , .4 , .2],'HandleVisibility','off');
obj.tn2a   = uicontrol('Style','togglebutton','String','ion','parent',tempSelect,...
    'FontWeight','bold','FontUnits','normalized','FontSize',.6,'Callback',...
    {@(src,event)changeTemp(obj,src)},'Units','normalized','Position',[ .55 , .31 , .4 , .2],'HandleVisibility','off');

obj.other =  uicontrol('Style','Radio','String','','parent',tempSelect,...
    'Callback',{@(src,event)changeTemp(obj,src)},'FontWeight','bold','FontUnits','normalized','FontSize',.8,'Units','normalized','Position',[ .08 , .06 , .4 , .2],'HandleVisibility','off');
obj.otherVar = uicontrol('parent',tempSelect,'Units', 'normalized','Style','pushbutton',...
    'FontUnits','normalized','FontSize',.5,'String','not selected','Position',[ .21 , .07 , .73 , .17 ],...
    'Callback',{@(src,event)selectNonTemp(obj,src,event)},'FontWeight','bold');

set( obj.noTemp , 'value' , 1 )


% ===================
%  selection buttons
% ===================

settingSelect = uibuttongroup('Parent',obj.RTTsidebar,...
    'Position',[ .3 .47 .658 .318 ]);

htext2 = uicontrol('parent',settingSelect,'Units', 'normalized','FontWeight','bold','HorizontalAlignment','center',...
    'FontUnits','normalized','FontSize',.8,'Style','text','String','Settings','Position',[ 0 , .87 , 1 , .091 ]);


htext3 = uicontrol('parent',settingSelect,'Units', 'normalized','FontWeight','bold','HorizontalAlignment','center',...
    'FontUnits','normalized','FontSize',.8,'Style','text','String','Mode','Position',[ 0 , .755 , .5 , .088 ]);

obj.modeButton = uicontrol('parent',settingSelect,'Units', 'normalized','Style','pushbutton',...
    'FontUnits','normalized','FontSize',.5,'String','REGIONS','Position',[ .5 , .755 , .4 , .088 ],...
    'Callback',{@(src,event)changeMode(obj)},'FontWeight','bold');


htext4 = uicontrol('parent',settingSelect,'Units', 'normalized','FontWeight','bold','HorizontalAlignment','center',...
    'FontUnits','normalized','FontSize',.77,'Style','text','String','Rad','Position',[ 0 , .633 , .5 , .088 ]);

obj.radScaleButton = uicontrol('parent',settingSelect,'Units', 'normalized','Style','pushbutton',...
    'FontUnits','normalized','FontSize',.5,'String','LIN','Position',[ .5 , .633 , .4 , .088 ],...
    'Callback',{@(src,event)changeRadiusScale(obj)},'FontWeight','bold');


htext5 = uicontrol('parent',settingSelect,'Units', 'normalized','FontWeight','bold','HorizontalAlignment','center',...
    'FontUnits','normalized','FontSize',.8,'Style','text','String','Time','Position',[ 0 , .516 , .5 , .088 ]);

obj.timeScaleButton = uicontrol('parent',settingSelect,'Units', 'normalized','Style','pushbutton',...
    'FontUnits','normalized','FontSize',.5,'String','LIN','Position',[ .5 , .516 , .4 , .088 ],...
    'Callback',{@(src,event)changeTimeScale(obj)},'FontWeight','bold');


htext6 = uicontrol('parent',settingSelect,'Units', 'normalized','FontWeight','bold','HorizontalAlignment','center',...
    'FontUnits','normalized','FontSize',.8,'Style','text','String','Temp','Position',[ 0 , .394 , .5 , .088 ]);

obj.tempScaleButton = uicontrol('parent',settingSelect,'Units', 'normalized','Style','pushbutton',...
    'FontUnits','normalized','FontSize',.5,'String','LIN','Position',[ .5 , .394 , .4 , .088 ],...
    'Callback',{@(src,event)changeTempScale(obj)},'FontWeight','bold');


htext7 = uicontrol('parent',settingSelect,'Units', 'normalized','FontWeight','bold','HorizontalAlignment','center',...
    'FontUnits','normalized','FontSize',.8,'Style','text','String','Lims','Position',[ 0 , .272 , .5 , .088 ]);

obj.tempLimitsButton = uicontrol('parent',settingSelect,'Units', 'normalized','Style','pushbutton',...
    'FontUnits','normalized','FontSize',.5,'String','AUTO','Position',[ .5 , .272 , .4 , .088 ],...
    'Callback',{@(src,event)changeTempLimits(obj)},'FontWeight','bold');


htext8 = uicontrol('parent',settingSelect,'Units', 'normalized','FontWeight','bold','HorizontalAlignment','center',...
    'FontUnits','normalized','FontSize',.8,'Style','text','String','Tone','Position',[ 0 , .15 , .5 , .088 ]);

obj.tempShadingButton = uicontrol('parent',settingSelect,'Units', 'normalized','Style','pushbutton',...
    'FontUnits','normalized','FontSize',.5,'String','SMOOTH','Position',[ .5 , .15 , .4 , .088 ],...
    'Callback',{@(src,event)changeTone(obj)},'FontWeight','bold');


obj.sliderBar = uicontrol('Style','Slider','SliderStep',[.05 .1],'String','temp visibility','parent',settingSelect,...
    'Units','normalized','Min',0,'Max',1,'Value',obj.scalVal,'Position',[.05,.035,.9,.08],...
    'HandleVisibility','off','Callback',{@(src,event)sliderFork(obj,src)});


% ===============
%  other buttons
% ===============

otherButtons = uipanel('Parent',obj.RTTsidebar,...
    'Position', [.3 .308 .658 .14]);

obj.autoRefreshButton = uicontrol('parent',otherButtons,'Units', 'normalized','Style','togglebutton',...
    'String','Auto Refresh','Position',[ .05 , .55 , .9 , .35 ],...
    'FontUnits','normalized','FontSize',.35,'Callback',{@(src,event)autoPlot(obj)});

obj.restartPlotButton = uicontrol('parent',otherButtons,'Units', 'normalized','Style','pushbutton',...
    'String','Restart Plot','Position',[ .05 , .1 , .9 , .35 ],...
    'FontUnits','normalized','FontSize',.35,'Callback',{@(src,event)restartPlot(obj)});


% ==============
%  push buttons
% ==============

obj.pushButtons = uibuttongroup('Parent',obj.RTTsidebar,...
    'Position', [ .3 .02 .658 .268 ]);

obj.openFileButton = uicontrol('parent',obj.pushButtons,'Units', 'normalized','Style','pushbutton',...
    'String','<html><center>Open<br>File','Position',[ .05 , .67 , .42 , .3 ],...
    'FontUnits','normalized','FontSize',.195,'Callback',{@(src,event)openBuckyFile(obj,src,event)});

obj.plotMultButton = uicontrol('parent',obj.pushButtons,'Units', 'normalized','Style','pushbutton',...
    'String','<html><center>Plot<br>Mult','Position',[ .53 , .67 , .42 , .3 ],...
    'FontUnits','normalized','FontSize',.195,'Callback',{@(src,event)plotMult(obj)});

obj.customOptsButton = uicontrol('parent',obj.pushButtons,'Units', 'normalized','Style','pushbutton',...
    'String','<html><center>Man.<br>Opts','Position',[ .05 , .355 , .42 , .3 ],...
    'FontUnits','normalized','FontSize',.19,'Callback',{@(src,event)customOpts(obj)});

obj.customZoomButton = uicontrol('parent',obj.pushButtons,'Units', 'normalized','Style','pushbutton',...
    'String','<html><center>Man.<br>Zoom','Position',[ .53 , .355 , .42 , .3 ],...
    'FontUnits','normalized','FontSize',.19,'Callback',{@(src,event)customZoom(obj)});

obj.reloadDataButton = uicontrol('parent',obj.pushButtons,'Units', 'normalized','Style','pushbutton',...
    'String','<html><center>Redo<br>Data','Position',[ .05 , .035 , .42 , .3 ],...
    'FontUnits','normalized','FontSize',.195,'Callback',{@(src,event)reloadData(obj)});

obj.snapShotButton = uicontrol('parent',obj.pushButtons,'Units', 'normalized','Style','pushbutton',...
    'String','<html><center>Snap<br>Shot','Position',[ .53 , .035 , .42 , .3 ],...
    'FontUnits','normalized','FontSize',.195,'Callback',{@(src,event)snapShot(obj)});

end