function plotAlot(obj,src,~)

varList = qwer.query(obj.mainFile) ;

thisFig = figure('Name','Plot Alot','NumberTitle','off','menubar', 'none') ;
hListBox = uicontrol('Style','listbox','String',varList(:,1),'units','normalized','Position',[ 0 0 .3 1]);
hListBox = uicontrol('Style','listbox','String',varList(:,1),'units','normalized','Position',[.3 0 .3 1]);

handles.radio(1) = uicontrol('Style', 'radiobutton', ...
    'Callback', @sin, ...
    'Units',    'pixels', ...
    'Position', [10, 10, 80, 22], ...
    'String',   'radio 1', ...
    'Value',    1);

handles.radio(2) = uicontrol('Style', 'radiobutton', ...
    'Callback', @sin, ...
    'Units',    'pixels', ...
    'Position', [10, 40, 80, 22], ...
    'String',   'radio 2', ...
    'Value',    0);

alotIcon    =  imread('imageOfAlot.jpg') ;
alotGrid    =  axes('Units','normalized','Position',[.6,.001,.4,.3]);
alotButton  =  image(alotIcon);

set(gca,'XTick',[],'YTick',[])

set(alotGrid,'LineWidth',2)
set(alotButton,'ButtonDownFcn',{@(src,event)plotMult(obj)})

end